# Generated by Django 5.0.6 on 2024-10-02 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='clien',
            new_name='userADRESS',
        ),
    ]
