# Generated by Django 5.0.6 on 2024-10-19 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custm', '0002_rename_clien_useradress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradress',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
