# Generated by Django 5.0.6 on 2024-12-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custm', '0004_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
