# Generated by Django 5.0.6 on 2024-12-04 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='produit',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='product.produit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='quantiti',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
