# Generated by Django 5.0.6 on 2024-08-14 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_order_quantiti_dele'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dele',
            name='order_number',
        ),
        migrations.AddField(
            model_name='dele',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.prod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dele',
            name='quantiti',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
