# Generated by Django 5.2 on 2025-08-05 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_paymenthistory_price_paymenthistory_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likeprod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likeprod',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
