# Generated by Django 5.0.6 on 2025-08-06 20:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_category_image_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="image",
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
