# Generated by Django 5.0.6 on 2024-10-26 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custm', '0003_alter_useradress_state'),
        ('product', '0002_category_alter_produit_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custm.useradress'),
            preserve_default=False,
        ),
    ]
