# Generated by Django 5.0.6 on 2024-08-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_dele_order_number_dele_produit_dele_quantiti'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dele',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='dele',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='dele',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='dele',
            name='quantiti',
        ),
        migrations.RemoveField(
            model_name='dele',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dele',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='dele',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Shipped', 'Shipped')], max_length=20),
        ),
    ]
