# Generated by Django 5.0.6 on 2025-08-06 20:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_productimage_image_alter_brand_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
