# Generated by Django 5.0.6 on 2024-10-27 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custm', '0003_alter_useradress_state'),
        ('product', '0004_paymenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='product',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='custm.useradress'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='ooder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1),
        ),
        migrations.DeleteModel(
            name='PayPalTransaction',
        ),
    ]
