# Generated by Django 5.0.6 on 2024-12-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_order_status_remove_paymenthistory_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattr',
            name='price',
        ),
        migrations.AddField(
            model_name='produit',
            name='price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
