# Generated by Django 5.0.6 on 2024-12-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productattr_price_produit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='ooder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cart'),
        ),
    ]
