# Generated by Django 5.0.6 on 2024-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_paymenthistory_ooder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
