# Generated by Django 5.0.6 on 2024-12-01 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
