# Generated by Django 5.0.6 on 2024-12-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'delevred'), ('F', 'Failed')], default='P', max_length=1),
        ),
    ]
